version: 2.1
executors:
  base:
    docker:
      - image: hyphe/ci-base-images:0.5.0 
commands: 
  init:
    description: 'sets up the environment'
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}
            - yarn-cache-master
      - run:
          name: install dependencies
          command: |
            yarn --pure-lockfile
            lerna bootstrap -- --pure-lockfile
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ .BuildNum }}
          paths:
            - /home/circleci/.cache/yarn/v1
jobs:
  test:
    executor: base
    steps:
      - init
      - run:
          name: unit tests
          command: yarn test
      # sometimes building breaks even if tests are green, this way we make sure builds wont fail
      - run:
          name: build test
          command: yarn build
  deploy:
    executor: base
    steps:
      - init
      - run:
          name: unit tests
          command: yarn test
      - run:
          name: deploy
          command: yarn deploy
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
           requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
