version: 2
jobs:
  build:
    docker:
      - image: hyphe/ci-base-images:0.5.0
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}
            - yarn-cache-master
      - run:
          name: install dependencies
          command: |
            yarn --pure-lockfile
            lerna bootstrap -- --pure-lockfile
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ .BuildNum }}
          paths:
            - /home/circleci/.cache/yarn/v1
      - run:
          name: unit tests
          command: yarn test
  # deploy:
  #   docker:
  #     - image: hyphe/ci-base-images:0.5.0
  #   steps:
  #     - checkout
  #     - setup_remote_docker
  #     - restore_cache:
  #         keys:
  #           - yarn-cache-master
  #     - run:
  #         name: install dependencies
  #         command: |
  #           yarn --pure-lockfile
  #           lerna bootstrap -- --pure-lockfile
  #     - save_cache:
  #         key: yarn-cache-master-{{ .BuildNum }}
  #         paths:
  #           - /home/circleci/.cache/yarn/v1
  #     - run:
  #         name: build
  #         command: ./bin/run-on-ci.sh build
  #     - run:
  #         name: deploy
  #         command: ./bin/run-on-ci.sh deploy
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      # - deploy:
      #     filters:
      #       tags:
      #         ignore: nothing
